apiVersion: apps/v1
kind: Deployment
metadata:
  name: stakater-backend-deployment
spec:
  selector:
    matchLabels:
      app: stakater-backend
  replicas: 2
  template:
    metadata:
      labels:
        app: stakater-backend
    spec:
      containers:
        - name: stakater-backend
          image: stakater-backend-node
          ports:
            - containerPort: 3005